module.exports = {
	MAUTIC_BASE_URL: 'https://mautic.acadevor.com/',
	MAUTIC_PUBLIC_KEY: 'MAUTIC_PUBLIC_KEY',
	MAUTIC_SECRET_KEY: 'MAUTIC_SECRET_KEY',
	ACCESS_TOKEN: 'ACCESS_TOKEN',
	REFRESH_TOKEN: 'REFRESH_TOKEN',
};
